# Generated by Django 5.2.10 on 2026-01-18 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='creado_el',
            new_name='creada_el',
        ),
        migrations.AddField(
            model_name='perfil',
            name='actualizada_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='parametros.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='parametros.sucursal'),
        ),
    ]
