# Generated by Django 5.2.10 on 2026-01-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_empresa_direccion_alter_empresa_rut'),
        ('parametros', '0005_sync_sucursal_timestamps'),
    ]

    operations = [
    ]
