# Generated by Django 5.2.10 on 2026-01-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_merge_20260118_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='actualizada_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='creada_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
