# Generated by Django 5.2.10 on 2026-01-22 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_alter_sucursal_actualizada_el_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('max_usuarios', models.PositiveIntegerField(default=1)),
                ('precio_mensual', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'max_usuarios', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=20)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_parametros', related_query_name='suscripcion_parametros', to='parametros.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.plan')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
