# Generated by Django 5.2.10 on 2026-04-19 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0008_viaje'),
        ('taller', '0012_conductor_tipo_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_recorridos', models.PositiveIntegerField(help_text='Kilómetros recorridos en el viaje')),
                ('total_combustible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_peajes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mantencion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.vehiculo')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo_analytics', to='operaciones.estatusoperacionalviaje')),
            ],
            options={
                'verbose_name': 'Costo por Viaje',
                'verbose_name_plural': 'Costos por Viaje',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento de la carga')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_combustible', to='taller.vehiculo')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.estatusoperacionalviaje')),
            ],
            options={
                'verbose_name': 'Gasto Combustible',
                'verbose_name_plural': 'Gastos Combustible',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoPeaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ruta', models.CharField(help_text='Ej: Ruta 5, tramo Los Vilos - La Serena', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_peaje', to='taller.vehiculo')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.estatusoperacionalviaje')),
            ],
            options={
                'verbose_name': 'Gasto Peaje',
                'verbose_name_plural': 'Gastos Peaje',
                'ordering': ['-fecha'],
            },
        ),
    ]
