# Generated by Django 5.2.10 on 2026-04-15 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0008_viaje'),
        ('taller', '0010_repuestomantenimiento_costo_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteChofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('EN_CAMINO', 'En camino'), ('CARGANDO', 'Cargando'), ('DESCARGANDO', 'Descargando'), ('RETORNO', 'Retorno'), ('COMPLETADO', 'Completado')], default='PEND', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('lugar_carga', models.CharField(blank=True, max_length=255)),
                ('lugar_descarga', models.CharField(blank=True, max_length=255)),
                ('nro_guia', models.CharField(blank=True, max_length=50)),
                ('oc_edp', models.CharField(blank=True, max_length=50)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='taller.conductor')),
                ('estatus_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatusoperacionalviaje')),
            ],
        ),
        migrations.CreateModel(
            name='FotoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes_chofer/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api_movil.reportechofer')),
            ],
        ),
    ]
