# Generated by Django 5.2.10 on 2026-04-16 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0001_initial'),
        ('taller', '0011_conductor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionChofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='taller.conductor')),
            ],
            options={
                'verbose_name': 'Ubicación de Chofer',
                'verbose_name_plural': 'Ubicaciones de Choferes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
