# Generated by Django 5.2.8 on 2026-01-13 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Servicio')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Inicio Servicio')),
                ('fecha_termino', models.DateField(default=django.utils.timezone.localdate, verbose_name='Término Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Servicio')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='centro_comercio.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_inicio', '-creado_en'],
            },
        ),
    ]
