# Generated by Django 5.2.10 on 2026-04-09 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Código SII de la AFP', max_length=10, unique=True)),
                ('tasa_cotizacion', models.DecimalField(decimal_places=4, help_text='Ej: 0.1044 = 10.44%', max_digits=5)),
                ('comision', models.DecimalField(decimal_places=4, help_text='Ej: 0.0069 = 0.69%', max_digits=5)),
                ('comision_adicional', models.DecimalField(decimal_places=4, default=0, help_text='Comisión adicional si aplica', max_digits=5)),
                ('seguro_invalidez', models.DecimalField(decimal_places=4, default=0.0144, help_text='Seguro de invalidez y sobrevivencia (1.44%)', max_digits=5)),
                ('fecha_vigencia', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('HABER_IMPONIBLE', 'Haber Imponible'), ('HABER_NO_IMPONIBLE', 'Haber No Imponible'), ('DESCUENTO_LEGAL', 'Descuento Legal'), ('DESCUENTO_VOLUNTARIO', 'Descuento Voluntario'), ('APORTE_EMPLEADOR', 'Aporte Empleador')], max_length=30)),
                ('categoria', models.CharField(blank=True, choices=[('REMUNERACION', 'Remuneración Base'), ('HORAS_EXTRA', 'Horas Extra'), ('BONOS', 'Bonos'), ('MOVILIZACION', 'Movilización'), ('COLACION', 'Colación'), ('ASIGNACION', 'Asignación Familiar'), ('GRATIFICACION', 'Gratificación'), ('DESCUENTO', 'Descuentos Varios'), ('PRESTAMO', 'Préstamos'), ('CAJA_COMPENSACION', 'Caja de Compensación'), ('COOPERATIVA', 'Cooperativa')], max_length=30, null=True)),
                ('es_imponible', models.BooleanField(default=True)),
                ('es_tributable', models.BooleanField(default=True)),
                ('es_afecto_a_descuentos', models.BooleanField(default=True)),
                ('formula', models.TextField(blank=True, help_text='Ej: sueldo_base * 0.25', null=True)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo fijo'), ('HONORARIOS', 'Honorarios')], max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_beneficiario', models.CharField(max_length=12)),
                ('nombre_beneficiario', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=7)),
                ('monto_bruto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('monto_retencion', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_liquido', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('OTRO', 'Otro Sistema')], max_length=10)),
                ('plan', models.CharField(choices=[('BASE', 'Plan Base 7%'), ('COMPLEMENTARIO', 'Plan Complementario'), ('PREMIUM', 'Plan Premium')], default='BASE', max_length=20)),
                ('tasa_cotizacion', models.DecimalField(decimal_places=4, default=0.07, help_text='Ej: 0.07 = 7%', max_digits=5)),
                ('tasa_adicional', models.DecimalField(decimal_places=4, default=0, help_text='Para planes complementarios', max_digits=5)),
                ('monto_adicional', models.DecimalField(decimal_places=0, default=0, help_text='Monto fijo adicional si aplica', max_digits=10)),
                ('fecha_vigencia', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salud',
                'verbose_name_plural': 'Salud (Fonasa/Isapre)',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TramoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hasta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor', models.DecimalField(decimal_places=4, help_text='Factor multiplicador', max_digits=5)),
                ('rebaja', models.DecimalField(decimal_places=2, help_text='Rebaja en UTM', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tipo_jornada', models.CharField(choices=[('COMPLETA', 'Jornada Completa (45 hrs)'), ('PARCIAL', 'Jornada Parcial'), ('ART_22', 'Artículo 22 (sin jornada máxima)')], max_length=20)),
                ('horas_semanales', models.IntegerField(default=45)),
                ('es_articulo_22', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('afp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='remuneraciones.afp')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='remuneraciones.empleado')),
                ('salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='remuneraciones.salud')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, help_text='Formato YYYY-MM', max_length=7)),
                ('total_haberes', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=0, max_digits=12)),
                ('liquido_pagar', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='remuneraciones.contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='remuneraciones.empleado')),
            ],
            options={
                'ordering': ['-periodo', 'contrato__empleado__apellidos'],
                'unique_together': {('contrato', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneraciones.concepto')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='remuneraciones.liquidacion')),
            ],
        ),
    ]
