# Generated by Django 5.2.10 on 2026-04-11 16:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_comercio', '0006_cotizacion_condicion_venta_cotizacioncuota'),
        ('operaciones', '0008_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(choices=[('33', 'Factura Afecta (33)'), ('34', 'Factura Exenta (34)'), ('39', 'Boleta (39)'), ('61', 'Nota de Crédito (61)'), ('56', 'Nota de Débito (56)')], max_length=2, unique=True)),
                ('ultimo_folio', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(choices=[('33', 'Factura Afecta (33)'), ('34', 'Factura Exenta (34)'), ('39', 'Boleta (39)'), ('61', 'Nota de Crédito (61)'), ('56', 'Nota de Débito (56)')], default='33', max_length=2)),
                ('folio', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('razon_social_emisor', models.CharField(default='TRANSCAP SpA', max_length=200)),
                ('rut_emisor', models.CharField(default='76.123.456-7', max_length=12)),
                ('giro_emisor', models.CharField(default='Transporte de carga por carretera', max_length=100)),
                ('razon_social_cliente', models.CharField(max_length=200)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('giro_cliente', models.CharField(blank=True, max_length=100)),
                ('direccion_cliente', models.CharField(blank=True, max_length=200)),
                ('comuna_cliente', models.CharField(blank=True, max_length=100)),
                ('ciudad_cliente', models.CharField(blank=True, max_length=100)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('EMI', 'Emitida (sin SII)'), ('ENV', 'Enviada al SII'), ('ACE', 'Aceptada por SII'), ('REC', 'Rechazada por SII'), ('ANU', 'Anulada')], default='BOR', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='centro_comercio.cliente')),
                ('viajes', models.ManyToManyField(blank=True, related_name='facturas', to='operaciones.viaje')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(default='VIAJE', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('monto_iva', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guia', to='facturacion.factura')),
            ],
        ),
    ]
