# Generated by Django 5.2.10 on 2026-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0007_bitacora_factura_bitacora_facturado'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='viajes',
            field=models.ManyToManyField(blank=True, related_name='facturas', to='bitacora.bitacora'),
        ),
    ]
