# Generated by Django 5.2.8 on 2026-01-14 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('glosa', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORR', 'Borrador'), ('PROC', 'En proceso'), ('PAGA', 'Pagado'), ('ANUL', 'Anulado')], default='BORR', max_length=4)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EDPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(choices=[('EFEC', 'Efectivo'), ('TRAN', 'Transferencia'), ('TARJ', 'Tarjeta'), ('OTRO', 'Otro')], default='TRAN', max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='edp.edp')),
            ],
        ),
        migrations.CreateModel(
            name='EDPServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estadia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='edp.edp')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
        ),
    ]
