# Generated by Django 5.2.10 on 2026-03-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_alter_bitacora_destino_alter_bitacora_guias_raw_and_more'),
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edpservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edp_items', to='bitacora.bitacora'),
        ),
    ]
