# Generated by Django 5.2.10 on 2026-03-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
        ('edp', '0002_alter_edpservicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='edp',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edps', to='centro_comercio.cliente'),
        ),
        migrations.AddField(
            model_name='edp',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='giro_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='razon_social_snapshot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='rut_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='conductor_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='destino_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='fecha_arribo_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='fecha_carga_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='fecha_descarga_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='numero_guia_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='origen_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='rut_conductor_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='edpservicio',
            name='tracto_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
