# Generated by Django 5.2.10 on 2026-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_edp_cliente_edp_fecha_inicio_edp_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edp',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('FACT', 'Facturado'), ('NO_FACT', 'No facturado'), ('ANUL', 'Anulado')], default='BOR', max_length=7),
        ),
    ]
