# Generated by Django 5.2.8 on 2025-12-20 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoFacturacionGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('correlativo_diario', models.PositiveIntegerField(default=1)),
                ('nro_guia', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_viaje', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('GUIA', 'Guía emitida'), ('FACT', 'Facturado'), ('PAGO', 'Pagado'), ('OBS', 'Observado')], default='PEND', max_length=4)),
                ('prioridad', models.CharField(choices=[('NOR', 'Normal'), ('URG', 'Urgente')], default='NOR', max_length=3)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('bloqueado_desde', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efg_actualizados', to=settings.AUTH_USER_MODEL)),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efg_bloqueados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='operaciones.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efg_creados', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_destino', to='operaciones.ciudad')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_origen', to='operaciones.ciudad')),
            ],
            options={
                'ordering': ['-fecha', 'estado', 'prioridad', '-id'],
                'permissions': [('puede_ver_estado', 'Puede ver Estado Facturación/Guías'), ('puede_editar_estado', 'Puede editar Estado Facturación/Guías'), ('puede_desbloquear_estado', 'Puede desbloquear registros')],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'correlativo_diario'), name='uniq_efg_fecha_correlativo')],
            },
        ),
    ]
