# Generated by Django 5.2.8 on 2025-12-21 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tab', models.CharField(blank=True, default='', max_length=10)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Operaciones',
                'verbose_name_plural': 'Sesiones Operaciones',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
