# Generated by Django 5.2.8 on 2025-12-22 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_sesionoperaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha', models.DateField(blank=True, db_index=True, null=True)),
                ('tab', models.CharField(blank=True, default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Operaciones',
                'verbose_name_plural': 'Sesiones Operaciones',
            },
        ),
        migrations.DeleteModel(
            name='SesionOperaciones',
        ),
        migrations.AddIndex(
            model_name='sessionoperaciones',
            index=models.Index(fields=['last_seen'], name='operaciones_last_se_b3eaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoperaciones',
            index=models.Index(fields=['fecha', 'tab'], name='operaciones_fecha_84ec33_idx'),
        ),
    ]
