# Generated by Django 5.2.10 on 2026-03-03 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_sessionoperaciones_delete_sesionoperaciones_and_more'),
        ('taller', '0008_repuestomantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusOperacionalViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('turno', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('estado_texto', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estatus_viajes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estatus_operacional', to='taller.conductor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estatus_viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('rampla', models.ForeignKey(blank=True, help_text='Vehículo tipo SEMIRREMOLQUE (rampla).', limit_choices_to={'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_rampla', to='taller.vehiculo')),
                ('tracto', models.ForeignKey(blank=True, help_text='Vehículo tipo TRACTO (patente).', limit_choices_to={'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_tracto', to='taller.vehiculo')),
            ],
            options={
                'ordering': ['-fecha', 'turno', 'conductor__apellidos', 'conductor__nombres'],
                'permissions': [('puede_ver_estatus_viajes', 'Puede ver Estatus de Viajes (Operaciones)'), ('puede_editar_estatus_viajes', 'Puede editar Estatus de Viajes (Operaciones)')],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'turno', 'conductor'), name='uniq_estatus_fecha_turno_conductor')],
            },
        ),
    ]
