# Generated by Django 5.2.10 on 2026-03-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_estatusoperacionalviaje'),
        ('taller', '0008_repuestomantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatusoperacionalviaje',
            options={'ordering': ['fecha', 'turno', 'conductor__apellidos', 'conductor__nombres'], 'permissions': [('puede_ver_estatus_viajes', 'Puede ver estatus de viajes'), ('puede_editar_estatus_viajes', 'Puede editar estatus de viajes')]},
        ),
        migrations.RemoveConstraint(
            model_name='estatusoperacionalviaje',
            name='uniq_estatus_fecha_turno_conductor',
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estatus_viajes', to='taller.conductor'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='estado_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='rampla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estatus_rampla', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='tracto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estatus_tracto', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='turno',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], db_index=True, max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='estatusoperacionalviaje',
            unique_together={('fecha', 'turno', 'conductor')},
        ),
    ]
