# Generated by Django 5.2.10 on 2026-03-13 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
        ('operaciones', '0005_alter_estatusoperacionalviaje_options_and_more'),
        ('taller', '0008_repuestomantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatusoperacionalviaje',
            options={'ordering': ['-fecha', 'turno', 'conductor__apellidos', 'conductor__nombres'], 'permissions': [('puede_ver_estatus_viajes', 'Puede ver Estatus de Viajes (Operaciones)'), ('puede_editar_estatus_viajes', 'Puede editar Estatus de Viajes (Operaciones)')]},
        ),
        migrations.AlterUniqueTogether(
            name='estatusoperacionalviaje',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_viajes', to='centro_comercio.cliente'),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='estado_carga',
            field=models.CharField(choices=[('DESCARGADO', 'Descargado'), ('CAMINO_DESCARGAR', 'Camino a descargar'), ('RETORNO_VACIO', 'Retorno vacío'), ('CARGADO', 'Cargado'), ('EN_RUTA', 'En ruta'), ('OTRO', 'Otro')], default='OTRO', max_length=25),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='estado_guia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='fecha_carga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='fecha_descarga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='lugar_carga',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='lugar_descarga',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='nro_guia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estatusoperacionalviaje',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estatus_operacional', to='taller.conductor'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='rampla',
            field=models.ForeignKey(blank=True, help_text='Vehículo tipo SEMIRREMOLQUE (rampla).', limit_choices_to={'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_rampla', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='tracto',
            field=models.ForeignKey(blank=True, help_text='Vehículo tipo TRACTO (patente).', limit_choices_to={'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_tracto', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='turno',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], db_index=True, default='AM', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='estatusoperacionalviaje',
            constraint=models.UniqueConstraint(fields=('fecha', 'turno', 'conductor'), name='uniq_estatus_fecha_turno_conductor'),
        ),
    ]
