# Generated by Django 5.2.10 on 2026-03-22 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_estatusoperacionalviaje_options_and_more'),
        ('taller', '0009_alter_mantenimiento_costo_mano_obra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadofacturacionguia',
            options={'ordering': ['-fecha', 'estado', 'prioridad', '-id']},
        ),
        migrations.AlterModelOptions(
            name='estatusoperacionalviaje',
            options={'ordering': ['-fecha', 'turno', 'conductor__apellidos', 'conductor__nombres']},
        ),
        migrations.AlterModelOptions(
            name='sessionoperaciones',
            options={},
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='rampla',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_rampla', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatusoperacionalviaje',
            name='tracto',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_tracto', to='taller.vehiculo'),
        ),
    ]
