# Generated by Django 5.2.8 on 2026-01-09 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT inválido. Formato esperado: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('giro', models.CharField(blank=True, default='', max_length=255, verbose_name='Giro')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('localidad', models.CharField(blank=True, default='', max_length=120, verbose_name='Localidad')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
    ]
