# Generated by Django 5.2.8 on 2026-01-09 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_hasta', models.DateField(default=django.utils.timezone.localdate)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terminos', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('ACEP', 'Aceptada'), ('ANUL', 'Anulada')], default='PEND', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='centro_comercio.cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exento', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centro_comercio.cotizacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
