# Generated by Django 5.2.10 on 2026-03-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('comision_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Comisión %')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Comisión %'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='glosa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Glosa'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='recargo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Recargo %'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sucursal',
            field=models.CharField(blank=True, default='MATRIZ', max_length=100, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Descuento $'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='centro_comercio.vendedor', verbose_name='Vendedor'),
        ),
    ]
