# Generated by Django 5.2.10 on 2026-04-07 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0003_vendedor_cotizacion_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razon_social'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='giro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='glosa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='recargo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sucursal',
            field=models.CharField(blank=True, default='MATRIZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='centro_comercio.vendedor'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='unidad',
            field=models.CharField(blank=True, default='Unidad', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='valor_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión %'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
