# Generated by Django 5.2.10 on 2026-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0004_alter_cliente_options_remove_cotizacion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número'),
        ),
    ]
