# Generated by Django 5.2.10 on 2026-04-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_comercio', '0005_cotizacion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condicion_venta',
            field=models.CharField(choices=[('CONT', 'Contado'), ('CRED', 'Crédito'), ('OTRO', 'Otro')], default='CRED', max_length=4, verbose_name='Condición de Venta'),
        ),
        migrations.CreateModel(
            name='CotizacionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de cuota')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='centro_comercio.cotizacion')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['fecha'],
            },
        ),
    ]
