# Generated by Django 5.2.10 on 2026-01-21 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0007_alter_sucursal_actualizada_el_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('max_usuarios', models.PositiveIntegerField(default=1)),
                ('max_empresas', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=12)),
                ('inicio', models.DateField(default=django.utils.timezone.now)),
                ('fin', models.DateField(blank=True, null=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='parametros.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plan')),
            ],
        ),
    ]
