# Generated by Django 5.2.10 on 2026-01-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_plan_suscripcion'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-activo', 'max_usuarios', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-inicio']},
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', related_query_name='suscripcion', to='parametros.empresa'),
        ),
    ]
