# Generated by Django 5.2.10 on 2026-01-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_alter_plan_options_alter_suscripcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden', 'max_usuarios', 'nombre']},
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_anual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
