# Generated by Django 5.2.8 on 2025-11-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('licencia_clase', models.CharField(blank=True, help_text='Ej: A2, A3, A5, etc.', max_length=20, null=True)),
                ('licencia_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento de la licencia', null=True)),
                ('activo', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='RutaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('kilometros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ruta de viaje',
                'verbose_name_plural': 'Rutas de viaje',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=15, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('tipo', models.CharField(blank=True, help_text='Bus, camión, camioneta, automóvil, etc.', max_length=50, null=True)),
                ('km_actual', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje actual')),
                ('nro_motor', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° motor')),
                ('nro_chasis', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° chasis')),
                ('capacidad', models.CharField(blank=True, help_text='Toneladas / pasajeros, etc.', max_length=50, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('aseguradora', models.CharField(blank=True, help_text='Compañía de seguros', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_TALLER', 'En taller'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='ACTIVO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LICENCIA', 'Licencia de conducir'), ('CERT_MED', 'Certificado médico'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/conductores/')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='taller.conductor')),
            ],
            options={
                'verbose_name': 'Documento de conductor',
                'verbose_name_plural': 'Documentos de conductores',
            },
        ),
        migrations.CreateModel(
            name='MultaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('infraccion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='taller.conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='taller.vehiculo')),
            ],
            options={
                'verbose_name': 'Multa de conductor',
                'verbose_name_plural': 'Multas de conductores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=15)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('km_programado', models.PositiveIntegerField(blank=True, null=True)),
                ('km_real', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PLANIFICADO', max_length=15)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='taller.taller')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='taller.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada', '-fecha_real'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERMISO', 'Permiso de circulación'), ('REVISION', 'Revisión técnica'), ('SEGURO_OBL', 'Seguro obligatorio'), ('SEGURO_VOL', 'Seguro voluntario'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='taller.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento de vehículo',
                'verbose_name_plural': 'Documentos de vehículos',
            },
        ),
    ]
