# Generated by Django 5.2.8 on 2025-11-21 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutaviaje',
            options={'ordering': ['origen', 'destino', 'nombre'], 'verbose_name': 'Ruta de viaje', 'verbose_name_plural': 'Rutas de viaje'},
        ),
        migrations.RemoveField(
            model_name='rutaviaje',
            name='kilometros',
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Distancia estimada (km)'),
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='duracion_estimada',
            field=models.DurationField(blank=True, help_text='Ej: 2:30:00 para 2 horas 30 min', null=True, verbose_name='Duración estimada'),
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='rutaviaje',
            name='peajes_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peajes aprox. ($)'),
        ),
        migrations.AlterField(
            model_name='rutaviaje',
            name='destino',
            field=models.CharField(max_length=100, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='rutaviaje',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la ruta'),
        ),
        migrations.AlterField(
            model_name='rutaviaje',
            name='origen',
            field=models.CharField(max_length=100, verbose_name='Origen'),
        ),
    ]
