# Generated by Django 5.2.8 on 2025-11-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_rutaviaje_options_remove_rutaviaje_kilometros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código interno')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente semirremolque')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Remolque / Semirremolque',
                'verbose_name_plural': 'Remolques / Semirremolques',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='CoordinacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(verbose_name='Fecha carga')),
                ('fecha_descarga', models.DateField(verbose_name='Fecha descarga')),
                ('sobreestadia_dias', models.IntegerField(blank=True, help_text='Días adicionales respecto a la descarga esperada', null=True, verbose_name='Sobreestadía (días)')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_asignados', to='taller.conductor', verbose_name='Conductor')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinaciones', to='taller.rutaviaje', verbose_name='Ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_asignados', to='taller.vehiculo', verbose_name='Tracto camión')),
                ('remolque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_asignados', to='taller.remolque', verbose_name='Semirremolque')),
            ],
            options={
                'verbose_name': 'Coordinación de viaje',
                'verbose_name_plural': 'Coordinación de viajes',
                'ordering': ['-fecha_carga', 'conductor__apellidos'],
            },
        ),
    ]
