# Generated by Django 5.2.8 on 2025-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_remolque_coordinacionviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio_comercial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año comercial'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción equipo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_equipo',
            field=models.CharField(blank=True, choices=[('NUEVO_SIN_USO', 'Nuevo sin uso'), ('USADO', 'Usado'), ('REACONDICIONADO', 'Reacondicionado')], help_text='Ej: Nuevo sin uso, Usado, Reacondicionado', max_length=20, null=True, verbose_name='Estado equipo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='familia_equipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Familia equipo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='it_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IT / Código interno'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_neto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio neto de compra'),
        ),
    ]
