# Generated by Django 5.2.8 on 2025-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_vehiculo_anio_comercial_vehiculo_descripcion_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='anio_comercial',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='familia_equipo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='it_codigo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio_neto',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='es_remolque',
            field=models.BooleanField(default=False, verbose_name='Es semirremolque / rampla'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_remolque',
            field=models.CharField(blank=True, help_text='Ej: Plataforma, baranda, rampla, etc.', max_length=100, null=True, verbose_name='Tipo semirremolque'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion_equipo',
            field=models.CharField(blank=True, help_text='Ej: Semirremolque 3 ejes Randon, barandas metálicas…', max_length=200, null=True, verbose_name='Descripción equipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_equipo',
            field=models.CharField(blank=True, choices=[('NUEVO', 'Nuevo sin uso'), ('USADO_BUENO', 'Usado buen estado'), ('USADO_REGULAR', 'Usado estado regular'), ('USADO_MALO', 'Usado mal estado')], help_text='Ej: Nuevo sin uso, usado, etc.', max_length=20, null=True, verbose_name='Estado equipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, help_text='Bus, camión, camioneta, automóvil, semirremolque, etc.', max_length=50, null=True),
        ),
    ]
