# Generated by Django 5.2.8 on 2025-11-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_remove_vehiculo_anio_comercial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoconductor',
            options={'ordering': ['conductor', 'fecha_vencimiento'], 'verbose_name': 'Documento de conductor', 'verbose_name_plural': 'Documentos de conductores'},
        ),
        migrations.AlterModelOptions(
            name='documentovehiculo',
            options={'ordering': ['vehiculo', 'fecha_vencimiento'], 'verbose_name': 'Documento de vehículo', 'verbose_name_plural': 'Documentos de vehículos'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'ordering': ['nombre'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.RemoveField(
            model_name='coordinacionviaje',
            name='remolque',
        ),
        migrations.AddField(
            model_name='coordinacionviaje',
            name='semirremolque_vehiculo',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_asignados_semirremolque', to='taller.vehiculo', verbose_name='Semirremolque'),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_asignados_tracto', to='taller.vehiculo', verbose_name='Tracto camión'),
        ),
    ]
