# Generated by Django 5.2.8 on 2025-11-29 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_alter_documentoconductor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinacionviaje',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Coordinación de viaje', 'verbose_name_plural': 'Coordinaciones de viaje'},
        ),
        migrations.RemoveField(
            model_name='coordinacionviaje',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='coordinacionviaje',
            name='semirremolque_vehiculo',
        ),
        migrations.RemoveField(
            model_name='coordinacionviaje',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='es_remolque',
        ),
        migrations.AddField(
            model_name='coordinacionviaje',
            name='semirremolque',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_semirremolque', to='taller.vehiculo'),
        ),
        migrations.AddField(
            model_name='coordinacionviaje',
            name='tracto_camion',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_tracto', to='taller.vehiculo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_coordinados', to='taller.conductor'),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='fecha_descarga',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha descarga'),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinaciones', to='taller.rutaviaje'),
        ),
        migrations.AlterField(
            model_name='coordinacionviaje',
            name='sobreestadia_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sobreestadia (días)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='km_programado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje programado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='km_real',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje real'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('OTRO', 'Otro')], default='PREVENTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion_equipo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción equipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_equipo',
            field=models.CharField(blank=True, choices=[('NUEVO', 'Nuevo sin uso'), ('USADO', 'Usado'), ('REACONDICIONADO', 'Reacondicionado')], help_text='Ej: Nuevo sin uso, usado, etc.', max_length=20, null=True, verbose_name='Estado equipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('TRACTO', 'Tracto camión'), ('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('AUTOMOVIL', 'Automóvil'), ('SEMIRREMOLQUE', 'Semirremolque / rampla'), ('OTRO', 'Otro')], default='CAMION', help_text='Ej: Tracto, camión, semirremolque, etc.', max_length=20),
        ),
    ]
