# Generated by Django 5.2.8 on 2025-12-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('taller', '0007_alter_coordinacionviaje_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_mantenimientos', to='inventario.bodega')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='taller.mantenimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_mantenimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Repuesto utilizado en mantenimiento',
                'verbose_name_plural': 'Repuestos utilizados en mantenimientos',
            },
        ),
    ]
