# Generated by Django 5.2.10 on 2026-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_alter_mantenimiento_costo_mano_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestomantenimiento',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='repuestomantenimiento',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
