# Generated by Django 5.2.10 on 2026-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_conductor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='tipo_ficha',
            field=models.CharField(blank=True, choices=[('EMPLEADO', 'Empleado'), ('PROVEEDOR', 'Proveedor'), ('CLIENTE_PROVEEDOR', 'Cliente - Proveedor'), ('CLIENTE', 'Cliente'), ('HONORARIO', 'Honorario')], default='EMPLEADO', help_text='Tipo de ficha del conductor', max_length=20, null=True),
        ),
    ]
