# Generated by Django 5.2.10 on 2026-04-12 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacora', '0007_bitacora_factura_bitacora_facturado'),
        ('taller', '0010_repuestomantenimiento_costo_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('OPER', 'Operacional'), ('ADMIN', 'Administrativo'), ('FIN', 'Financiero')], default='OPER', max_length=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor o razón social', max_length=200)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('documento', models.CharField(blank=True, help_text='Factura, Boleta, etc.', max_length=30)),
                ('nro_documento', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('CH', 'Cheque'), ('TC', 'Tarjeta Crédito')], max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('bitacora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitacora.bitacora')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.vehiculo')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral')], default='MENSUAL', max_length=10)),
                ('dia_pago', models.IntegerField(help_text='Día del mes (1-31) o -1 para último día')),
                ('activo', models.BooleanField(default=True)),
                ('ultima_generacion', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
            ],
        ),
    ]
