# Generated by Django 5.2.8 on 2026-01-15 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
        ('operaciones', '0003_sessionoperaciones_delete_sesionoperaciones_and_more'),
        ('taller', '0008_repuestomantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_arribo', models.DateField(blank=True, null=True)),
                ('fecha_descarga', models.DateField(blank=True, null=True)),
                ('nro_guias', models.CharField(blank=True, default='', help_text="Separar múltiples guías con '-' (ej: 3291-3296).", max_length=255, verbose_name='N° Guía/as')),
                ('oc_edp', models.CharField(blank=True, default='', help_text="Separar múltiples con '-' (ej: 3291-3296).", max_length=255, verbose_name='OC/EDP')),
                ('semirremolque', models.BooleanField(default=False)),
                ('con_estadia', models.BooleanField(default=False)),
                ('descripcion_trabajo', models.TextField(blank=True, default='', verbose_name='Descripción del trabajo')),
                ('tarifa_flete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estadia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('VIG', 'Vigente'), ('FAC', 'Facturado'), ('ANU', 'Anulado')], default='VIG', max_length=3)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='taller.conductor')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='centro_comercio.cliente')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_coordinadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_creadas', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_destino', to='operaciones.ciudad')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_origen', to='operaciones.ciudad')),
                ('rampla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_rampla', to='taller.vehiculo')),
                ('tracto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_tracto', to='taller.vehiculo')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='bitacora_bi_fecha_b672a3_idx'), models.Index(fields=['estado'], name='bitacora_bi_estado_f829a1_idx'), models.Index(fields=['cliente'], name='bitacora_bi_cliente_02311c_idx'), models.Index(fields=['chofer'], name='bitacora_bi_chofer__82d8c0_idx'), models.Index(fields=['tracto'], name='bitacora_bi_tracto__a14766_idx'), models.Index(fields=['origen'], name='bitacora_bi_origen__01e928_idx'), models.Index(fields=['destino'], name='bitacora_bi_destino_597ad3_idx')],
            },
        ),
    ]
