# Generated by Django 5.2.8 on 2026-01-15 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        ('centro_comercio', '0002_cotizacion_cotizacionitem'),
        ('operaciones', '0003_sessionoperaciones_delete_sesionoperaciones_and_more'),
        ('taller', '0008_repuestomantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='coordinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='taller.coordinacionviaje'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(choices=[('VIG', 'Vigente'), ('FAC', 'Facturado'), ('PAG', 'Pagado'), ('ANU', 'Anulado')], default='VIG', max_length=3),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nro_guias',
            field=models.CharField(blank=True, default='', help_text="Separar múltiples con '-' (ej: 3291-3296).", max_length=255, verbose_name='N° Guía/as'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='rampla',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_rampla', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tracto',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_tracto', to='taller.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['rampla'], name='bitacora_bi_rampla__7db9b3_idx'),
        ),
    ]
