# Generated by Django 5.2.8 on 2026-01-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_bitacora_coordinacion_alter_bitacora_estado_and_more'),
        ('taller', '0008_repuestomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, default='', max_length=50)),
                ('oc_edp', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_fecha_b672a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_estado_f829a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_cliente_02311c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_chofer__82d8c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_tracto__a14766_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_origen__01e928_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_destino_597ad3_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitacora',
            name='bitacora_bi_rampla__7db9b3_idx',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='con_estadia',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='nro_guias',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='oc_edp',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='semirremolque',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='total',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='taller.conductor'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='guias_raw',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='N° Guías (raw)'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='intermedio',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Intermedio'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='oc_edp_raw',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OC/EDP (raw)'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='coordinador',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='descripcion_trabajo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estadia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(choices=[('VIG', 'Vigente'), ('CER', 'Cerrada'), ('ANU', 'Anulada')], default='VIG', max_length=3),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='rampla',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'SEMIRREMOLQUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_rampla', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tarifa_flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tracto',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'TRACTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_tracto', to='taller.vehiculo'),
        ),
        migrations.AddField(
            model_name='bitacoradetalle',
            name='bitacora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bitacora.bitacora'),
        ),
    ]
