# Generated by Django 5.2.10 on 2026-01-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_bitacoradetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='guias_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='intermedio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='oc_edp_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
