# Generated by Django 5.2.10 on 2026-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_bitacora_estatus_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
