# Generated by Django 5.2.10 on 2026-04-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0006_alter_bitacora_fecha'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura que incluye este servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='facturacion.factura', verbose_name='Factura asociada'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='facturado',
            field=models.BooleanField(default=False, help_text='Indica si este servicio ya fue incluido en una factura', verbose_name='Facturado'),
        ),
    ]
